# Generated by Django 5.2 on 2025-05-02 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='images')),
                ('dealername', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dealer_registration',
            fields=[
                ('dealer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('GstNo', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fertilizer',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fertilizer_type', models.CharField(max_length=100)),
                ('nutrients', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('usage', models.CharField(max_length=200)),
                ('application_method', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=200)),
                ('benifits', models.CharField(max_length=200)),
                ('precautions', models.CharField(max_length=200)),
                ('suitablecrop', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stotageinstructions', models.CharField(max_length=200)),
                ('dealer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hired_labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('NumberOfLabour', models.IntegerField()),
                ('worktype', models.CharField(max_length=100)),
                ('hired_date', models.DateField()),
                ('image', models.ImageField(upload_to='images')),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationItem',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='labour_registration',
            fields=[
                ('labour_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('adharno', models.IntegerField(unique=True)),
                ('worktype', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='machinery',
            fields=[
                ('machine_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('specifications', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dealer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('owner_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pesticide',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('composition', models.CharField(max_length=100)),
                ('suitablecrop', models.CharField(max_length=200)),
                ('application_method', models.CharField(max_length=200)),
                ('precautions', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='irrigation_items/')),
                ('manufacturer', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dealer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=200)),
                ('cpassword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='seeds',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('seedname', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('seed_type', models.CharField(max_length=100)),
                ('germination_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('seed_treatment', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('manufacture', models.DecimalField(decimal_places=2, max_digits=5)),
                ('spacing', models.CharField(max_length=200)),
                ('harvest_time', models.CharField(max_length=200)),
                ('yield_per_hectare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dealer', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='hiredMachinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('contact', models.IntegerField()),
                ('machine_name', models.CharField(max_length=30)),
                ('hired_date', models.DateField()),
                ('useraddress', models.CharField(max_length=50)),
                ('machine_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.machinery')),
            ],
        ),
        migrations.AddField(
            model_name='machinery',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.owner'),
        ),
        migrations.CreateModel(
            name='rent_machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinename', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('machine_type', models.CharField(max_length=30)),
                ('charge', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('machine_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='sales_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('product_type', models.CharField(max_length=30)),
                ('total_sales', models.IntegerField()),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dealer_registration')),
            ],
        ),
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration')),
            ],
        ),
    ]
