# Generated by Django 5.2 on 2025-05-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='irrigationitem',
            name='discharge',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
