# Generated by Django 5.2 on 2025-05-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_fertilizer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer',
            old_name='benifits',
            new_name='benefits',
        ),
        migrations.RenameField(
            model_name='fertilizer',
            old_name='stotageinstructions',
            new_name='storageinstructions',
        ),
    ]
