# Generated by Django 5.2 on 2025-05-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_benifits_fertilizer_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='fertilizer_images/'),
        ),
    ]
