# Generated by Django 5.2 on 2025-05-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_irrigationitem_updated_at_and_more'),
        ('app', '0004_fertilizer_image'),
    ]

    operations = [
    ]
