# Generated by Django 5.2 on 2025-05-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20250512_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='irrigationitem',
            name='discharge',
            field=models.CharField(max_length=20),
        ),
    ]
