# Generated by Django 5.2 on 2025-05-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_irrigationitem_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationitem',
            name='image',
        ),
    ]
