# Generated by Django 5.2 on 2025-05-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_irrigationitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='irrigationitem',
            name='image',
            field=models.ImageField(default=True, null=True, upload_to='images'),
        ),
    ]
