# Generated by Django 5.2 on 2025-05-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_irrigationitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeds',
            name='germination_rate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='manufacture',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='yield_per_hectare',
            field=models.CharField(max_length=20),
        ),
    ]
