# Generated by Django 5.2 on 2025-05-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_seeds_germination_rate_alter_seeds_manufacture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
