# Generated by Django 5.2 on 2025-05-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_pesticide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
