# Generated by Django 5.2 on 2025-05-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_pesticide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_registration',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='labour_registration',
            name='labour_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
