# Generated by Django 5.2 on 2025-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_owner_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer_registration',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
